name: demo3
run-name: Pipeline run by @${{ github.actor }}
on:
  push:
    branches: ["main", "master"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: echo job
        run: sh demo.sh
