name: demo3

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:


jobs:
  echo-job:
    uses: dwarakanathreddy/workflows-reusable-test/.github/workflows/echo.yml@main
    
  monolith-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  oao-build:
    needs: [monolith-build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  banker-build:
    needs: [monolith-build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  oao-package:
    needs: [oao-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: echo job
        run: sh demo.sh
  banker-package:
    needs: [banker-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: echo job
        run: sh demo.sh
  dev-deploy:
    needs: [oao-package, banker-package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy
        run: sh demo.sh
  prod-deploy:
    environment:
      name: production
    needs: [oao-package, banker-package]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: actions/checkout@v4
        with:
          name: production
