
on:
  push:
    branches: ["main", "master"]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: HELLO

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: echo job
        run: sh demo.sh
